---
title: "Works Cited"
---

:::{ .callout-warning}
## Disclaimer
***Under Construction***
:::

Below are the Data Management Plans and projects presented throughout the website. We have organized it by agency/group. Where available, full references and DOIs are included.


| Project Name                                                                                                                                             | PI(s)                                               | Agency    | Award(s)                                    | Reference / DOI                                                                                                                                |
| -------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------- | --------- | ------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------- |
| Collaborative Research: Defining the Role of the Pangenome in *Emiliania huxleyi* Ecology and Biogeography                                               | Alexander, H. & Dyhrman, S.                         | BCO-DMO   | NSF OCE-1948025 & OCE-1948409               | [https://www.bco-dmo.org/project/789439](https://www.bco-dmo.org/project/789439)                                                               |
| [Untitled]                                                                                                                                               | Arnosti                                             | BCO-DMO   |                                             |                                                                                                                                                |
| [Untitled]                                                                                                                                               | Bianchi                                             | BCO-DMO   |                                             |                                                                                                                                                |
| EAGER Collaborative Research: Early career chief scientist training for biological and chemical oceanographers                                           | Church, M., Goetze, E., Ferrón, S., & White, A.     | BCO-DMO   | NSF OCE-1911831 & OCE-1911990               | [https://www.bco-dmo.org/project/805876](https://www.bco-dmo.org/project/805876)                                                               |
| CAREER: Multiple Scales of Nitrogen Cycle in Oxygen Minimum Zones                                                                                        | Bianchi, D.                                         | BCO-DMO   | NSF OCE-1847687                             | [https://www.bco-dmo.org/project/809665](https://www.bco-dmo.org/project/809665)                                                               |
| Do fine-scale water column structure and particle aggregations favor gelatinous-dominated food webs in subtropical continental shelf environments?       | Greer, A., Brandes, J., Frischer, M., & Treible, L. | BCO-DMO   | NSF OCE-2244690                             | [https://www.bco-dmo.org/project/897221](https://www.bco-dmo.org/project/897221)                                                               |
| Trajectories in functional diversity after disturbance at vents on the East Pacific Rise                                                                 | Mullineaux, L. & Beaulieu, S                        | BCO-DMO   | NSF OCE-1829773                             | [https://www.bco-dmo.org/project/783674](https://www.bco-dmo.org/project/783674)                                                               |
| Collaborative Research: Life after Death: Do Inactive Sulfides Fuel a Unique Ecosystem at the Deep Seafloor?                                             | Mullineaux, L., Beaulieu, S., & Sylvan, J.          | BCO-DMO   | NSF OCE-2152453 & OCE-2152422               | [https://www.bco-dmo.org/project/873319](https://www.bco-dmo.org/project/873319)                                                               |
| Collaborative Research: Underexplored Connections between Nitrogen and Trace Metal Cycling in Oxygen Minimum Zones Mediated by Metalloenzyme Inventories | Saito, M., Breier, J., Santoro, A., & Jakuba, M.    | BCO-DMO   | NSF OCE-1924554, OCE-1924508, & OCE-1924512 | [https://www.bco-dmo.org/project/806565](https://www.bco-dmo.org/project/806565)                                                               |
| Dispersal, connectivity and local adaptation along an extreme environmental gradient                                                                     | Reitzel, A.                                         | BCO-DMO   | NSF OCE-1924498                             | [https://www.bco-dmo.org/project/817793](https://www.bco-dmo.org/project/817793)                                                               |
| Coastal Ocean Processes of North Greenland                                                                                                               | Muenchow, A.                                        | NSF ADC   |                                             | Muenchow, A. 2023. Coastal Ocean Processes of North Greenland. ADC. [https://doi.org/10.48321/D1R316](https://doi.org/10.48321/D1R316)         |
| Northeast US Shelf (NES) Long-Term Ecological Research (LTER) Phase II                                                                                   | Sosik                                               | NSF LTER  |                                             |                                                                                                                                                |
| Northern Gulf of Alaska (NGA) Long-Term Ecological Research (LTER) Phase II                                                                              | Turner, C.                                          | NSF LTER  |                                             | Turner, C. 2023. NGA LTER Phase II Data Management Plan. NSF LTER. [https://doi.org/10.48321/D10DBEE0C5](https://doi.org/10.48321/D10DBEE0C5) |
| Long-Term Dynamics of a Coral Reef Ecosystem Moorea Coral Reef (MCR) Long Term Ecological Research (LTER)                                                | Schmitt                                             | NSF LTER  |                                             |                                                                                                                                                |
| Airborne and Satellite Investigation of Asian Air Quality (ASIA-AQ)                                                                                      | Kusterer (?)                                        | NASA      |                                             |                                                                                                                                                |
| Southern California Coastal Ocean Observing System (SCCOOS)                                                                                              | [Unknown]                                           | NOAA IOOS |                                             |                                                                                                                                                |
