---
title: "References"
---

*Please request additional terms / resources using [GitHub issues](https://github.com/ESIPFed/esipDMP/issues/new/choose).*

## Acronyms

|           |                                                             |                          |
|-----------|-------------------------------------------------------------|--------------------------|
| ADC	    | Arctic Data Center                                          | https://arcticdata.io/   |
| ASIA-AQ	| Airborne and Satellite Investigation of Asian Air Quality   |                          |
| BCO-DMO	| Biological and Chemical Oceanography Data Management Office | https://www.bco-dmo.org/ |
| IOOS	    | U.S. Integrated Ocean Observing System                      |                          | 
| LTER	    | Long Term Ecological Research Network	                      | https://lternet.edu/     |
| MCR	    | Moorea Coral Reef                                           |                          | 
| NASA   	| National Aeronautics and Space Administration |  | 
| NCEI   	| National Centers for Environmental Information |  | 
| NOAA  	| National Oceanic and Atmospheric Administration |  | 
| NGA	    | Northern Gulf of Alaska | | 
| NSF	    | National Science Foundation | https://www.nsf.gov/ | 
| ORCID     | Open Researcher and Contributor ID |  |
| ROR       | Research Organization Registry | |
| SCCOOS	| Southern California Coastal Ocean Observing System | |


## DMP References

Title: Collaborative Research: Defining the Role of the Pangenome in Emiliania huxleyi Ecology and Biogeography
Lead Author: Alexander
Agency: BCO-DMO

Title: 
Lead Author: Arnosti
Agency: BCO-DMO

Title:
Lead Author: Bianchi
Agency: BCO-DMO

Title:
Lead Author: Church
Agency: BCO-DMO

Title:
Lead Author: Bianchi
Agency: BCO-DMO

Title:
Lead Author: Greer
Agency: BCO-DMO

Title: Trajectories in functional diversity after disturbance at vents on the East Pacific Rise
Lead Author: Mullineaux
Agency: BCO-DMO

Title: Trajectories in functional diversity after disturbance at vents on the East Pacific Rise
Lead Author: Mullineaux
Agency: BCO-DMO

Title: Life After Death: Do Inactive Sulfides Fuel a Unique Ecosystem at the Deep Seafloor?
Lead Author: Mullineaux
Agency: BCO-DMO

Title: Underexplored Connections between Nitrogen and Trace Metal Cycling
Lead Author: Saito
Agency: BCO-DMO

Title:
Lead Author: Reitzel
Agency: BCO-DMO

Title: Coastal Ocean Processes of North Greenland
Lead Author: Muenchow
Agency: NSF ADC
Full reference!
Muenchow. 2023. Coastal Ocean Processes of North Greenland. ADC. [https://doi.org/10.48321/D1R316](https://doi.org/10.48321/D1R316)

Title: Northeast US Shelf (NES) Long-Term Ecological Research (LTER) Phase II
Lead Author: Sosik
Agency: NSF LTER

Title: Northern Gulf of Alaska (NGA) Long-Term Ecological Research (LTER) Phase II
Lead Author: Turner
Agency: NSF LTER
Full reference! Turner. 2023. NGA LTER Phase II Data Management Plan. NSF LTER. [https://doi.org/10.48321/D10DBEE0C5](https://doi.org/10.48321/D10DBEE0C5) 

Title: Long-Term Dynamics of a Coral Reef Ecosystem Moorea Coral Reef (MCR) Long Term Ecological Research (LTER)
Lead Author: Schmitt
Agency: NSF LTER

Title: Airborne and Satellite Investigation of Asian Air Quality (ASIA-AQ)
Lead Author: Kusterer (?)
Agency: NASA

Title: Southern California Coastal Ocean Observing System (SCCOOS)
Lead Author: ?
Agency: NOAA IOOS





