---
title: "Roles and Responsibilities"
---

*Thoughtfully deciding who will fill the roles and have the responsibilities for data sharing and stewarding earth science data is critical. While all persons are expected to practice good data stewardship, this section asks for the contact info for the key project personnel [name, ORCID, affiliation, ROR, contact(email, phone)]. In addition, this section asks what plans are in place for handling turnover in personnel while maintaining the key roles and responsibilities.  *

::: {.callout-tip}
## Relevant literature
Wood-Charlson EM, Crockett Z, Erdmann C, Arkin AP, Robinson CB (2022) **Ten simple rules for getting and giving credit for data**. PLOS Computational Biology 18(9): e1010476. <https://doi.org/10.1371/journal.pcbi.1010476>
:::

## Personnel

*The key roles are included below: Principal Investigator, Data Manager, Point of Contact for the DMP.  Other roles that could be included here include: Data Provider, Data Collector, Data Analyst, Data Engineer, GIS Analyst, Contractor, Consultant.*

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[contributor](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_contributor_table)

-   Consider using persistent identifiers (PIDs), such as [ORCiD](https://orcid.org), to identify and disambiguate personnel


### Principle Investigator 

-   Ensures the DMP is followed by the research team.

::: {.callout-note}
### BCO-DMO: [Mullineaux #2453](https://drive.google.com/file/d/1-N-bHKeJbC1QTouZVT5Ae2MMSAG9CEYA/view?usp=share_link) 
*Lead PI will ensure compliance to this data management plan.*
:::  

### Data Manager

-   Oversees data management practices.

-   May ensure compliance with the Data Management Plan (DMP).

-   May be the primary individual responsible for DMP updates.

::: {.callout-note}
### BCO-DMO: [Mullineaux #2453](https://drive.google.com/file/d/1-N-bHKeJbC1QTouZVT5Ae2MMSAG9CEYA/view?usp=share_link)
-  *Observations at seafloor: All PIs*
-  *Imagery at seafloor - PI3 and PI4*
-  *Physical sample cataloging:*
    -  *PI1 will obtain IGSNs for rock samples; PI2 will provide unique*

-  Animal specimen identifiers:
    -  *Each PI will catalog his/her respective subsamples associated to identifier, when applicable.*
-  *Data for animals - PI-3 and PI-4*
-  *Data for microbes - PI-1 and PI-2*
-  *Data for minerals - PI-3*
-  *Derived data from integrating: All PIs*
:::

### Point of Contact for the DMP

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[contact](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_contact_table)

-  Primary individual responsible for DMP updates and communication.

-  May ensure the DMP is followed by the research team.

::: {.callout-note}
### BCO-DMO: [Mullineaux #2453](https://drive.google.com/file/d/1-N-bHKeJbC1QTouZVT5Ae2MMSAG9CEYA/view?usp=share_link):
-  *Lead PI will ensure compliance to this data management plan.*
-  *Details of external parties involved in data management.*
:::

-   Serves as the primary communication person for the DMP

-   May be the primary individual responsible for DMP updates.


### Third Party/Contractor/Consultant

-   External party that contributes to the project


## Plan for Personnel Turnover/Transfer

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[preservation_statement](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_preservation)

-  Procedures for transferring responsibilities in case of personnel changes.

-  Documentation of roles and access permissions.


## Funder identification

-  Persistent identifiers (PIDs) help identify the support for the research  
    -   [RAID](https://raid.org) - a project meta-PID  
    -   [RRID](https://www.rrids.org)  
    -   [DataCite (DOIs)](https://datacite.org)  




