---
title: "Access to Research Outputs"
---

### Access

*Describe how access to the research outputs will be provided (e.g., by publishing with a public domain license in a robust repository).  *

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[distribution](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#distribution_table) 

-  Consider using persistent identifiers (PIDs) for access protocols. 


### Sharing

*Describe any requirements to share the data from the project. Such requirements might come from a funder, participating organization, government agency, or other relevant entity. *

-  Mechanisms for sharing outputs (e.g., repositories, cloud storage).

::: {.callout-note}
## BCO-DMO: [Church](../references_resources/works_cited.qmd){target="_blank"}
*To increase accessibility to project data and the dissemination of our research findings—particularly among scientists from developing countries—we will make every effort to publish our results as open-access articles or within open-access journals.*
:::

### Archive(s)

*Describe the steps your project team will take to secure long-term availability of project data, and research outputs. This might include publishing data in robust repositories with strong sustainability plans, archiving back-up copies of data in long-term institutional cloud storage, including data maintenance in future funding requests and institutional budgets, and creating a long-term plan to ensure data remain available as staff change and data needs change.  *

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[preservation_statement](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_preservation) 

-  Where the data will be stored (e.g., institutional repository, public archive).

::: {.callout-note}
## BCO-DMO: [Saito](../references_resources/works_cited.qmd){target="_blank"}
*R2R will ensure that the original underway measurements are archived permanently at NCEI and/or NGDC as appropriate. BCO-DMO will also ensure that project data are submitted to the appropriate national data archive. The PI will work with R2R and BCO-DMO to ensure data are archived appropriately and that proper and complete documentation are archived along with the data. All processed data will be submitted to BCO-DMO. Sequence data will be submitted to NCBI and raw mass spectrometry data will be submitted to ProteomeXchange.*
:::
::: {.callout-note}   
## BCO-DMO: [Reitzel](../references_resources/works_cited.qmd){target="_blank"}
*Sequence data will be archived at NCBI GenBank or SRA, code will be archived on GitHub and processed data files (e.g., vcf files) will be deposited in Dryad. BCO-DMO ensures that the data are archived properly at the appropriate National Data Archive for long-term archive preservation.*
:::

-  Consider using repository persistent identifiers (PIDs) to identify where data will be stored or deposited
    -  Repository PIDs can be found at [Re3data](https://www.re3data.org)


### Timeline for Availability/Access

*Describe any timelines for making data available that are mandated (e.g., by a funder) or planned by the project leads.  *

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[distribution](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#distribution_table)/[available_until](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#distribution_available_until)

-  When will products be shared or published (e.g., immediately, after embargo period).

::: {.callout-note}
## BCO-DMO: [Church](../references_resources/works_cited.qmd){target="_blank"}
*All of the data generated in this study will be made publicly available upon publication in a peer-reviewed journal, or within two years of the completion of the project. […] Shipboard underway data will be made available within one year via the Rolling Deck to Repository.*
:::

::: {.callout-note}
## BCO-DMO: [Greer](../references_resources/works_cited.qmd){target="_blank"}
*Once the data have been collected and quality controlled, we will ensure all data are publicly available within two years. In general, we do not intend to impose any data embargos, with the exception of student generated data that will be used for the completion of student theses and publications.*
:::

### License

*Describe any licensing requirements from funders, participating organizations, or government agencies, including a species license (e.g. [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en)) or data use agreement.  *

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[license](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#license_table)

-  Licensing terms (e.g., Creative Commons, MIT License).

::: {.callout-note}
## BCO–DMO: [Church](../references_resources/works_cited.qmd){target="_blank"}
*All data from this project are considered within the public domain for all not-for-profit uses and there will be no permission restrictions placed on use of the data.*
:::

:::{.commentbox}
::::{.commentbox-header}
:::::{.commentbox-icon}
:::::
Comments
::::
::::{.commentbox-body}
**These authors use descriptive language but do not explicitly declare a license.  Data reuse terms would be clearer if the authors stated a license (e.g. [CC-BY](https://creativecommons.org/licenses/by/4.0/)).**
::::
:::

::: {.callout-note}
## [MCR-LTER](../references_resources/works_cited.qmd){target="_blank"}
*Our data access/data use policy is the Creative Commons license CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/). The user is free to use and adapt the data while giving appropriate credit without any other restrictions. In our data use policy, we make a few additional recommendations for collaboration and suggest that users contact the appropriate MCR personnel if they have any questions or concerns about the data, but these recommendations do not change the general license text.*
:::

### Restrictions / Confidentiality / Proprietary Business Info / Protection provisions

*Describe any restrictions, embargoes, or other methods that will be applied to the data and research outputs, the methods for applying them, and for how long they will be applied. *


See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[distribution](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#distribution_table)/[data_access](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#distribution_data_access)

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[personal_data](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_personal_data)

See DMP Common Standard: [dmp](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dmp_table)/[dataset](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_table)/[sensitive_data](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#dataset_sensitive_data)

-  Limitations on access due to confidentiality (e.g. personal data) or proprietary concerns (e.g. business-critical data).  

::: {.callout-note}
## BCO-DMO: [Greer](../references_resources/works_cited.qmd){target="_blank"}
*We do not expect that the data we will generate will require any exceptional arrangements due to questions of ethical restrictions or release of indigenous knowledge.*
:::

::: {.callout-note}
## BCO-DMO:  [Church](../references_resources/works_cited.qmd){target="_blank"}
*There are no ethical and privacy issues with these data. There are no human research subjects in our study. The dataset from this project will not be copyrighted.*
:::

:::{.commentbox}
::::{.commentbox-header}
:::::{.commentbox-icon}
:::::
Comments
::::
::::{.commentbox-body}
**These authors use descriptive language but do not explicitly declare a license.  Data reuse terms would be clearer if the authors stated a license (e.g. [CC-BY](https://creativecommons.org/licenses/by/4.0/)).**
::::
:::
